TOPDIR=./../..

TARGET=main

LIBPATH=$(TOPDIR)/lib
INCPATH=$(TOPDIR)/inc
EXEPATH=$(TOPDIR)/bin

CFLAGS= -I$(TOPDIR)/inc -g -ggdb3
LDFLAGS= -lpthread -lfirst -lsecond  -g

include $(TOPDIR)/Makefile.env
